### PR TITLE
Upstream Release 3.1

### PR DESCRIPTION
**Pull request by shaardie**
This patch updates the packaging to version 3.1.

### CODE REVIEW

**Comment by shaardie** [comment]
One thing we could think about is copying the old config `etc/pyca.conf` to `etc/pyca/pyca.conf` to ease upgrading.

**Comment by shaardie** [comment]
Also I would like to make aware for the following lines during the [build](https://app.circleci.com/pipelines/github/elan-ev/pyca-debian/60/workflows/53e14eb5-8423-47d7-b9eb-6672c17a4553/jobs/84/parallel-runs/0/steps/0-104):

```
npm WARN npm npm does not support Node.js v10.21.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/ 
WARN notice [SECURITY] http-proxy has the following vulnerability: 1 high. Go here for more details: https://www.npmjs.com/advisories?search=http-proxy&version=1.18.1 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
WARN notice [SECURITY] set-value has the following vulnerability: 1 high. Go here for more details: https://www.npmjs.com/advisories?search=set-value&version=2.0.1 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
```

Not sure about the consequences. One thing we could do is actually build with Debian Unstable, since the npm version is newer. People could still install the package on Stable.

**Comment by lkiesow** [comment]
I don't think that the newer versions of node should be a problem. But it's interesting to see that there is a mismatch since both tools are usually shipped together.

I also find the security warning curious since npm does not work me:

```
% npm audit
                                                                                
                       === npm audit security report ===                        
                                                                                
found 0 vulnerabilities
 in 971 scanned packages
```
…but since it's only a dependency for development/debugging, it is also not critical for production.

**Comment by lkiesow** [comment]
Reading through this, this patch seems reasonable.
Feel free to merge it.
Let me know when I should test it :D

**Comment by shaardie** [comment]
@lkiesow If you want to, you can test it right away. The built package is stored as a build artifact, see https://app.circleci.com/pipelines/github/elan-ev/pyca-debian/60/workflows/53e14eb5-8423-47d7-b9eb-6672c17a4553/jobs/84/artifacts, which you can use to install the new version using `dpkg -i <filename>.deb`.

I am going install it in Ubuntu and Raspbian and also try a upgrade from an old package and merge then.

**Comment by lkiesow** [comment]
Did test a fresh install and an upgrade on Raspberry Pi OS.
Unfortunately, I get internal server errors when accessing the user interface.
Specifically, the `/api/name` and `/api/metrics` endpoints break.

<details>
<summary>/api/name error logs</summary>

```
[pyca.config:138:logger_init()] [INFO] Log level set to info
[pyca.config:98:update_configuration()] [INFO] Configuration loaded from /etc/pyca/pyca.conf
…
[flask.app:1761:log_exception()] [ERROR] Exception on /api/name [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1974, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/usr/lib/python3/dist-packages/werkzeug/wrappers.py", line 921, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/usr/lib/python3/dist-packages/werkzeug/wrappers.py", line 59, in _run_wsgi_app
    return _run_wsgi_app(*args)
  File "/usr/lib/python3/dist-packages/werkzeug/test.py", line 923, in run_wsgi_app
    app_rv = app(environ, start_response)
TypeError: 'dict' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3/dist-packages/pyca/ui/utils.py", line 20, in decorated
    return f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pyca/ui/utils.py", line 31, in decorated
    response = f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pyca/ui/jsonapi.py", line 43, in get_name
    return make_response({'meta': {'name': config()['agent']['name']}})
  File "/usr/lib/python3/dist-packages/flask/helpers.py", line 213, in make_response
    return current_app.make_response(args)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1982, in make_response
    reraise(TypeError, new_error, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 34, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1974, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/usr/lib/python3/dist-packages/werkzeug/wrappers.py", line 921, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/usr/lib/python3/dist-packages/werkzeug/wrappers.py", line 59, in _run_wsgi_app
    return _run_wsgi_app(*args)
  File "/usr/lib/python3/dist-packages/werkzeug/test.py", line 923, in run_wsgi_app
    app_rv = app(environ, start_response)
TypeError: 'dict' object is not callable
The view function did not return a valid response. The return type must be a string, tuple, Response instance, or WSGI callable, but it was a dict.
[werkzeug:88:_log()] [INFO] 127.0.0.1 - - [14/Jun/2020 23:57:57] "GET /api/name HTTP/1.1" 500 -
```

</summary>

**Comment by lkiesow** [comment]
It seems like the Flask version installed is too old. Raspberry Pi OS ships with 1.0.2 but the implicit conversions of doictionaries to JSON is a feature introduced in Flask 1.1.0:

https://stackoverflow.com/questions/57470020/when-you-return-a-dict-in-flask-is-jsonify-automatically-applied#comment104273727_57470213

**Comment by lkiesow** [comment]
The difference and the reason that all the old endpoints work is that they ann call `make_data_response` or `make_error_response` which both contain `jsonify`. So we either need to upgrade flask on Raspberry Pi OS or we release a 3.1 which includes `jsonify`. What do you think?

**Comment by shaardie** [comment]
@lkiesow We could patch this in the packaging for now and do not have to directly release a new version, but in the long term, I think we if we want to support Debian OSs, we have to fix this upstream. So I would suggest `jsonify` in upstream and a small patch for now in the packaging.

**Comment by shaardie** [comment]
I found another error. Seems like the `/api/metrics` endpoint fails, if the capture recording directory does not exists, which could be the case as long as no recording was started.

**Comment by shaardie** [comment]
I updated the packaging to 3.1

**Comment by shaardie** [comment]
Tested to install it under Ubuntu Docker and also tested to start the ui there with the command specified in the service file. Both work.

**Comment by lkiesow** [comment]
Tested on Raspberry Pi OS and Ubuntu 20.04 → Works

**Pull request merged**
